'use client';
import type { LifeData, Trip, Venue, Visit, Collection } from '../lib/types';
import { makeId, upsertTrip, upsertVenue, upsertVisit, upsertCollection, deleteCollection } from '../lib/data-store';
export function Trips(p:any){return <div className="page-stack"><section className="panel"><div className="panel-head"><div><div className="section-kicker">Organisation</div><h2>Trips</h2></div><button className="primary-btn" onClick={()=>p.setModal('trip')}>Create trip</button></div>{p.data.trips.map((t:Trip)=><div className="entity-row" key={t.id}><div><strong>{t.name}</strong><span>{t.startDate||'—'} → {t.endDate||'—'} · {t.country||'No location'}</span><small>{p.data.observations.filter((o:any)=>o.tripId===t.id).length} observations · {new Set(p.data.observations.filter((o:any)=>o.tripId===t.id).map((o:any)=>o.taxonId)).size} species</small></div><button className="secondary-btn" onClick={()=>{p.setActiveTrip(t.id);p.setTab('observations')}}>Start trip</button></div>)}{!p.data.trips.length&&<div className="empty mini"><strong>No trips yet</strong><span>Create a trip to group observations.</span></div>}</section></div>}
export function Venues(p:any){return <div className="page-stack"><section className="panel"><div className="panel-head"><div><div className="section-kicker">Places</div><h2>Locations & venues</h2></div><button className="primary-btn" onClick={()=>p.setModal('venue')}>Add venue</button></div>{p.data.venues.map((v:Venue)=><div className="entity-row" key={v.id}><div><strong>{v.name}</strong><span>{v.city||'—'} · {v.country||'—'} · {v.type}</span><small>{p.data.observations.filter((o:any)=>o.venueId===v.id).length} observations · {new Set(p.data.observations.filter((o:any)=>o.venueId===v.id).map((o:any)=>o.taxonId)).size} species</small></div><button className="secondary-btn" onClick={()=>p.setModal('visit')}>Start visit</button></div>)}{p.data.locations.map((v:any)=><div className="entity-row muted-row" key={v.id}><div><strong>{v.name}</strong><span>{v.city||'—'} · {v.country||'—'} · natural location</span></div></div>)}</section></div>}
export function Collections(p:any){return <div className="page-stack"><section className="panel"><div className="panel-head"><div><div className="section-kicker">Saved views</div><h2>Collections</h2></div><button className="primary-btn" onClick={()=>p.setModal('collection')}>New collection</button></div>{p.data.collections.map((c:Collection)=><div className="entity-row" key={c.id}><div><strong>{c.name}</strong><span>{c.description||'Saved query'}</span></div><button className="danger-btn" onClick={()=>p.persist(deleteCollection(c.id,p.data))}>Delete</button></div>)}{!p.data.collections.length&&<div className="empty mini"><strong>No saved lists</strong><span>Collections are query definitions, not copied data.</span></div>}</section></div>}
export function Taxonomy(p:any){const classes=[...new Set(p.list.map((x:any)=>x.taxon.className).filter(Boolean))].sort();return <div className="page-stack"><section className="panel"><div className="section-kicker">Taxonomy</div><h2>Taxonomy Explorer</h2><p className="max-copy">Browse the taxonomy represented by your canonical taxa. Remote completeness is only reported when a checklist denominator is available.</p>{classes.map((c:string)=><div className="rank-line" key={c}><span>{c}</span><strong>{p.list.filter((x:any)=>x.taxon.className===c).length} observed</strong></div>)}</section></div>}
export function Discover(p:any){const families=[...new Set(p.list.map((x:any)=>x.taxon.family).filter(Boolean))].sort();return <div className="page-stack"><section className="panel"><div className="section-kicker">Discovery</div><h2>What am I missing?</h2><p className="max-copy">The app does not fabricate a global denominator. Explore your represented taxonomy and turn canonical taxa into targets once a reliable source supplies them.</p>{families.slice(0,20).map((f:string)=><div className="discover-row" key={f}><strong>{f}</strong><span>{p.list.filter((x:any)=>x.taxon.family===f).length} observed species</span></div>)}</section></div>}
export function Countries(p:any){const rows=[...new Set(p.data.observations.map((o:any)=>o.country??o.locationSnapshot?.country).filter(Boolean) as string[])].map(country=>{const os=p.data.observations.filter((o:any)=>(o.country??o.locationSnapshot?.country)===country);const s=new Set(os.map((o:any)=>o.taxonId));return{country,obs:os.length,species:s.size};}).sort((a,b)=>b.species-a.species);return <div className="page-stack"><section className="panel"><div className="section-kicker">Geography</div><h2>Countries</h2><p className="muted">Observation countries only; this is not a separate visited-country record.</p>{rows.map(r=><div className="rank-line" key={r.country}><span>{r.country}</span><strong>{r.species} species · {r.obs} observations</strong></div>)}</section></div>}
export function Milestones(p:any){return <div className="page-stack"><section className="panel"><div className="section-kicker">Timeline</div><h2>Milestones</h2>{p.milestones.map((m:any)=><div className="milestone-row" key={m.id}><span>{m.date?.slice(0,4)||'—'}</span><div><strong>{m.title}</strong><small>{m.detail}</small></div></div>)}</section></div>}
