'use client';
import {useState} from 'react';
import {MapContainer,TileLayer,CircleMarker,Popup} from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import type {Collection,LifeData,Trip,Venue,VenueType,Visit} from '../lib/types';
import {deleteCollection} from '../lib/data-store';
import {buildLifeList,milestones as calcMilestones,taxonName,evaluateCollection} from '../lib/derived';
const id=(p:string)=>`${p}_${Date.now()}`;
export function Trips(p:any){return <div className="page-stack"><section className="panel"><div className="panel-head"><div><div className="section-kicker">Organisation</div><h2>Trips</h2></div><button className="primary-btn" onClick={()=>p.setModal('trip')}>Create trip</button></div>{p.data.trips.map((t:Trip)=><div className="entity-row" key={t.id}><div><strong>{t.name}</strong><span>{t.startDate||'—'} → {t.endDate||'—'} · {t.country||'No location'}</span><small>{p.data.observations.filter((o:any)=>o.tripId===t.id).length} observations · {new Set(p.data.observations.filter((o:any)=>o.tripId===t.id).map((o:any)=>o.taxonId)).size} species</small></div><button className="secondary-btn" onClick={()=>{p.setActiveTrip(t.id);p.setTab('observations')}}>Start trip</button></div>)}</section></div>}
export function Venues(p:any){return <div className="page-stack"><section className="panel"><div className="panel-head"><div><div className="section-kicker">Places</div><h2>Locations & venues</h2></div><button className="primary-btn" onClick={()=>p.setModal('venue')}>Add venue</button></div>{p.data.venues.map((v:Venue)=><div className="entity-row" key={v.id}><div><strong>{v.name}</strong><span>{v.city||'—'} · {v.country||'—'} · {v.type}</span><small>{p.data.observations.filter((o:any)=>o.venueId===v.id).length} observations · {new Set(p.data.observations.filter((o:any)=>o.venueId===v.id).map((o:any)=>o.taxonId)).size} species</small></div><button className="secondary-btn" onClick={()=>p.setModal('visit')}>Start visit</button></div>)}{p.data.locations.map((v:any)=><div className="entity-row muted-row" key={v.id}><div><strong>{v.name}</strong><span>{v.city||'—'} · {v.country||'—'} · natural location</span></div></div>)}</section></div>}
export function Collections(p:any){return <div className="page-stack"><section className="panel"><div className="panel-head"><div><div className="section-kicker">Saved views</div><h2>Collections</h2></div><button className="primary-btn" onClick={()=>p.setModal('collection')}>New collection</button></div>{p.data.collections.map((c:Collection)=><div className="entity-row" key={c.id}><div><strong>{c.name}</strong><span>{c.description||'Saved query'}</span><small>{evaluateCollection(p.data,c).length} species · derived automatically</small></div><button className="danger-btn" onClick={()=>p.persist(deleteCollection(c.id,p.data))}>Delete</button></div>)}</section></div>}
export function Taxonomy(p:any){const classes:string[]=[...new Set(p.list.map((x:any)=>String(x.taxon.className||'')).values()].filter(Boolean).sort();return <div className="page-stack"><section className="panel"><div className="section-kicker">Taxonomy</div><h2>Taxonomy Explorer</h2><p className="max-copy">Navigate the taxonomy represented by cached canonical taxa. Completeness is not fabricated where no defensible denominator is available.</p>{classes.map((c:string)=><div className="rank-line" key={c}><span>{c}</span><strong>{p.list.filter((x:any)=>x.taxon.className===c).length} observed</strong></div>)}</section></div>}
export function Discover(p:any){const families:string[]=[...new Set(p.list.map((x:any)=>String(x.taxon.family||'')).values()].filter(Boolean).sort();return <div className="page-stack"><section className="panel"><div className="section-kicker">Discovery</div><h2>What am I missing?</h2><p className="max-copy">Life only claims supported missing taxa when the underlying taxonomy provides a reliable denominator. These are represented families to explore next.</p>{families.slice(0,20).map((f:string)=><div className="discover-row" key={f}><strong>{f}</strong><span>{p.list.filter((x:any)=>x.taxon.family===f).length} observed species</span></div>)}</section></div>}
export function MapPage(p:any){const points=p.data.observations.filter((o:any)=>o.latitude!=null&&o.longitude!=null);return <div className="page-stack"><section className="panel"><div className="section-kicker">Geography</div><h2>Observation map</h2><div className="map-frame"><MapContainer center={[20,0]} zoom={2} className="leaflet-map"><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{points.map((o:any)=><CircleMarker key={o.id} center={[o.latitude,o.longitude]} radius={6}><Popup>{taxonName(p.data.taxa[o.taxonId])}<br/>{o.observedDate}</Popup></CircleMarker>)}</MapContainer></div><div className="muted">{points.length} mapped observations.</div></section></div>}
export function Countries(p:any){const rows:any[]=[...new Set(p.data.observations.map((o:any)=>o.country||o.locationSnapshot?.country).filter(Boolean))].map((country:any)=>{const obs=p.data.observations.filter((o:any)=>(o.country||o.locationSnapshot?.country)===country);return{country,obs:obs.length,species:new Set(obs.map((o:any)=>o.taxonId)).size}}).sort((a,b)=>b.species-a.species);return <div className="page-stack"><section className="panel"><div className="section-kicker">Geography</div><h2>Countries</h2><p className="muted">Countries represented by recorded observations; this is not a separate visited-country list.</p>{rows.map(r=><div className="rank-line" key={r.country}><span>{r.country}</span><strong>{r.species} species · {r.obs} observations</strong></div>)}</section></div>}
export function Stats(p:any){const list=buildLifeList(p.data);const years:string[]=[...new Set(p.data.observations.map((o:any)=>String(o.observedDate||'').slice(0,4)).filter(Boolean))].sort();return <div className="page-stack"><div className="stats-grid compact"><Stat value={list.length} label="Species"/><Stat value={p.data.observations.length} label="Observations"/><Stat value={new Set(list.map(x=>x.taxon.genus).filter(Boolean)).size} label="Genera"/><Stat value={new Set(list.map(x=>x.taxon.family).filter(Boolean)).size} label="Families"/></div><section className="panel"><div className="section-kicker">Temporal</div><h2>Additions by year</h2>{years.map(y=><div className="rank-line" key={y}><span>{y}</span><strong>{list.filter(x=>x.firstObservation.observedDate.startsWith(y)).length} species · {p.data.observations.filter((o:any)=>o.observedDate.startsWith(y)).length} observations</strong></div>)}</section></div>}
export function Milestones(p:any){return <div className="page-stack"><section className="panel"><div className="section-kicker">Timeline</div><h2>Milestones</h2>{calcMilestones(p.data).map(m=><div className="milestone-row" key={m.id}><span>{m.date?.slice(0,4)||'—'}</span><div><strong>{m.title}</strong><small>{m.detail}</small></div></div>)}</section></div>}
export function ImportExport(p:any){const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState<any>();return <div className="page-stack"><section className="panel"><div className="section-kicker">Data portability</div><h2>Import / Export</h2><div className="export-grid"><button className="export-card" onClick={()=>download('life.json',JSON.stringify(p.data,null,2),'application/json')}><strong>Export JSON</strong><span>Full dataset</span></button><button className="export-card" onClick={()=>download('life.csv',makeCSV(p.data),'text/csv')}><strong>Export CSV</strong><span>Observation table</span></button></div><div className="import-box"><input type="file" accept=".json,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="secondary-btn" onClick={async()=>file&&setPreview(require('../lib/import-export').importData(await file.text(),file.name.endsWith('.csv')?'csv':'json',p.data))}>Preview import</button>{preview&&<div className="notice"><span>{preview.observations} source · {preview.valid} valid · {preview.invalid} invalid</span><button className="primary-btn" onClick={()=>{p.persist(preview.data);setPreview(undefined)}}>Confirm import</button></div>}</div></section></div>}
export function SettingsPage(p:any){return <div className="page-stack"><section className="panel"><div className="section-kicker">Local-first</div><h2>Settings</h2><p className="max-copy">Your authoritative observations and canonical taxa remain in this browser. No account, cloud sync, or server database is used.</p></section></div>}
export function TripModal({open,onClose,onSave}:any){const[t,setT]=useState<any>({name:'',startDate:'',endDate:'',country:'',notes:''});if(!open)return null;return <Modal title="Create trip" onClose={onClose}><div className="form-stack"><label><span>Name</span><input value={t.name} onChange={e=>setT({...t,name:e.target.value})}/></label><div className="two-col"><label><span>Start</span><input type="date" value={t.startDate} onChange={e=>setT({...t,startDate:e.target.value})}/></label><label><span>End</span><input type="date" value={t.endDate} onChange={e=>setT({...t,endDate:e.target.value})}/></label></div><label><span>Country / location</span><input value={t.country} onChange={e=>setT({...t,country:e.target.value})}/></label><label><span>Notes</span><textarea value={t.notes} onChange={e=>setT({...t,notes:e.target.value})}/></label></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!t.name} onClick={()=>{onSave({...t,id:id('trip'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Save trip</button></div></Modal>}
export function VenueModal({open,onClose,onSave}:any){const[v,setV]=useState<any>({name:'',type:'Zoo',city:'',country:''});if(!open)return null;return <Modal title="Add venue" onClose={onClose}><div className="form-stack"><label><span>Name</span><input value={v.name} onChange={e=>setV({...v,name:e.target.value})}/></label><div className="two-col"><label><span>Type</span><select value={v.type} onChange={e=>setV({...v,type:e.target.value as VenueType})}>{['Zoo','Wildlife park','Reserve','Aquarium','Museum','Natural location','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Country</span><input value={v.country} onChange={e=>setV({...v,country:e.target.value})}/></label></div><label><span>City</span><input value={v.city} onChange={e=>setV({...v,city:e.target.value})}/></label></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!v.name} onClick={()=>{onSave({...v,id:id('venue'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Save venue</button></div></Modal>}
export function VisitModal({open,data,onClose,onSave}:any){const[v,setV]=useState<any>({venueId:'',date:new Date().toISOString().slice(0,10),notes:''});if(!open)return null;return <Modal title="Start visit" onClose={onClose}><div className="form-stack"><label><span>Venue</span><select value={v.venueId} onChange={e=>setV({...v,venueId:e.target.value})}><option value="">Select venue…</option>{data.venues.map((x:Venue)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Date</span><input type="date" value={v.date} onChange={e=>setV({...v,date:e.target.value})}/></label><label><span>Notes</span><textarea value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!v.venueId} onClick={()=>{onSave({...v,id:id('visit'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Start visit</button></div></Modal>}
export function CollectionModal({open,onClose,onSave}:any){const[c,setC]=useState<any>({name:'',description:'',queryDefinition:{}});if(!open)return null;return <Modal title="Save collection" onClose={onClose}><div className="form-stack"><label><span>Name</span><input value={c.name} onChange={e=>setC({...c,name:e.target.value})}/></label><label><span>Description</span><input value={c.description} onChange={e=>setC({...c,description:e.target.value})}/></label><div className="notice">Collections store only their query definition.</div></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!c.name} onClick={()=>{onSave({...c,id:id('collection'),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Save</button></div></Modal>}
function makeCSV(d:LifeData){return ['id,taxonId,date,observationType,count,country,notes',...d.observations.map(o=>[o.id,o.taxonId,o.observedDate,o.observationType,o.count,o.country||o.locationSnapshot?.country||'',o.notes].map(v=>`"${String(v).replaceAll('"','""')}"`).join(','))].join('\n')}
function download(name:string,text:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function Stat(p:any){return <div className="stat"><div className="stat-value">{p.value}</div><div className="stat-label">{p.label}</div></div>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><strong>{title}</strong><button className="icon-btn small" onClick={onClose}>×</button></div>{children}</div></div>}
