'use client';
import type { LifeData } from '../lib/types';
import { buildLifeList, queryObservations, milestones } from '../lib/derived';
import { exportCSV, exportJSON, importData } from '../lib/import-export';
import { MapContainer, TileLayer, CircleMarker, Popup } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
export function MapPage(p:any){const points=p.data.observations.filter((o:any)=>o.latitude!=null&&o.longitude!=null);return <div className="page-stack"><section className="panel"><div className="section-kicker">Geography</div><h2>Observation map</h2><div className="map-frame"><MapContainer center={[20,0]} zoom={2} className="leaflet-map"><TileLayer attribution="© OpenStreetMap contributors" url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/>{points.map((o:any)=><CircleMarker key={o.id} center={[o.latitude,o.longitude]} radius={6}><Popup>{p.data.taxa[o.taxonId]?.canonicalName}<br/>{o.observedDate}</Popup></CircleMarker>)}</MapContainer></div><div className="muted">{points.length} mapped observations. Species and life-list views can be filtered separately.</div></section></div>}
export function Stats(p:any){const list=buildLifeList(p.data);const years=[...new Set(p.data.observations.map((o:any)=>o.observedDate.slice(0,4)).filter(Boolean))].sort();return <div className="page-stack"><div className="stats-grid compact"><Stat value={list.length} label="Species"/><Stat value={p.data.observations.length} label="Observations"/><Stat value={new Set(list.map(x=>x.taxon.genus).filter(Boolean)).size} label="Genera"/><Stat value={new Set(list.map(x=>x.taxon.family).filter(Boolean)).size} label="Families"/></div><section className="panel"><div className="section-kicker">Temporal</div><h2>Additions by year</h2>{years.map(y=><div className="rank-line" key={y}><span>{y}</span><strong>{list.filter(x=>x.firstObservation.observedDate.startsWith(y)).length} species · {p.data.observations.filter((o:any)=>o.observedDate.startsWith(y)).length} observations</strong></div>)}</section><section className="panel"><div className="section-kicker">Observation type</div>{(['Wild','Captive','Semi-wild','Unknown'] as const).map(t=><div className="rank-line" key={t}><span>{t}</span><strong>{p.data.observations.filter((o:any)=>o.observationType===t).length}</strong></div>)}</section></div>}
export function ImportExport(p:any){const[file,setFile]=useStateFile();const[preview,setPreview]=useState<any>();const inspect=async()=>{if(!file)return;setPreview(importData(await file.text(),file.name.endsWith('.csv')?'csv':'json',p.data));};return <div className="page-stack"><section className="panel"><div className="section-kicker">Data portability</div><h2>Import / Export</h2><div className="export-grid"><button className="export-card" onClick={()=>download('life.json',exportJSON(p.data),'application/json')}><strong>Export JSON</strong><span>Full round-trip dataset</span></button><button className="export-card" onClick={()=>download('life.csv',exportCSV(p.data),'text/csv')}><strong>Export CSV</strong><span>Observation table</span></button></div><div className="import-box"><input type="file" accept=".json,.csv" onChange={e=>setFile(e.target.files?.[0]||null)}/><button className="secondary-btn" onClick={inspect}>Preview import</button>{preview&&<div className="notice"><span>{preview.observations} source observations · {preview.valid} valid · {preview.invalid} invalid</span><button className="primary-btn" onClick={()=>{p.persist(preview.data);setPreview(undefined)}}>Confirm import</button></div>}</div></section></div>}
function useStateFile(){const{useState}=require('react');return useState<any>(null);}
function download(name:string,text:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();}
function Stat(p:any){return <div className="stat"><div className="stat-value">{p.value}</div><div className="stat-label">{p.label}</div></div>}
export function SettingsPage(p:any){return <div className="page-stack"><section className="panel"><div className="section-kicker">Local-first</div><h2>Settings</h2><p className="max-copy">Canonical taxa and observations remain local. No authentication, cloud sync or server database is introduced.</p><div className="setting-actions"><button className="danger-btn" onClick={()=>{if(confirm('Clear all Life data?'))p.persist(require('../lib/data-store').clearData())}}>Clear local data</button></div></section></div>}
export function CollectionModal({open,onClose,onSave}:any){const{useState}=require('react');const[c,setC]=useState<any>({name:'',description:'',queryDefinition:{}});if(!open)return null;return <Modal title="Save collection" onClose={onClose}><div className="form-stack"><label><span>Name</span><input value={c.name} onChange={(e:any)=>setC({...c,name:e.target.value})}/></label><label><span>Description</span><input value={c.description} onChange={(e:any)=>setC({...c,description:e.target.value})}/></label><div className="notice">Only the query definition is stored; results are always recalculated.</div></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!c.name} onClick={()=>{onSave({...c,id:`collection_${Date.now()}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Save</button></div></Modal>}
export function TripModal({open,onClose,onSave}:any){const{useState}=require('react');const[t,setT]=useState<any>({name:'',startDate:'',endDate:'',country:'',notes:''});if(!open)return null;return <Modal title="Create trip" onClose={onClose}><div className="form-stack"><label><span>Name</span><input value={t.name} onChange={(e:any)=>setT({...t,name:e.target.value})}/></label><div className="two-col"><label><span>Start</span><input type="date" value={t.startDate} onChange={(e:any)=>setT({...t,startDate:e.target.value})}/></label><label><span>End</span><input type="date" value={t.endDate} onChange={(e:any)=>setT({...t,endDate:e.target.value})}/></label></div><label><span>Country / location</span><input value={t.country} onChange={(e:any)=>setT({...t,country:e.target.value})}/></label><label><span>Notes</span><textarea value={t.notes} onChange={(e:any)=>setT({...t,notes:e.target.value})}/></label></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!t.name} onClick={()=>{onSave({...t,id:`trip_${Date.now()}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Save</button></div></Modal>}
export function VenueModal({open,onClose,onSave}:any){const{useState}=require('react');const[v,setV]=useState<any>({name:'',type:'Zoo',city:'',country:''});if(!open)return null;return <Modal title="Add venue" onClose={onClose}><div className="form-stack"><label><span>Name</span><input value={v.name} onChange={(e:any)=>setV({...v,name:e.target.value})}/></label><div className="two-col"><label><span>Type</span><select value={v.type} onChange={(e:any)=>setV({...v,type:e.target.value})}>{['Zoo','Wildlife park','Reserve','Aquarium','Museum','Natural location','Other'].map(x=><option key={x}>{x}</option>)}</select></label><label><span>Country</span><input value={v.country} onChange={(e:any)=>setV({...v,country:e.target.value})}/></label></div><label><span>City</span><input value={v.city} onChange={(e:any)=>setV({...v,city:e.target.value})}/></label></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!v.name} onClick={()=>{onSave({...v,id:`venue_${Date.now()}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Save</button></div></Modal>}
export function VisitModal({open,data,onClose,onSave}:any){const{useState}=require('react');const[v,setV]=useState<any>({venueId:data.venues[0]?.id||'',date:new Date().toISOString().slice(0,10),notes:''});if(!open)return null;return <Modal title="Start visit" onClose={onClose}><div className="form-stack"><label><span>Venue</span><select value={v.venueId} onChange={(e:any)=>setV({...v,venueId:e.target.value})}>{data.venues.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label><span>Date</span><input type="date" value={v.date} onChange={(e:any)=>setV({...v,date:e.target.value})}/></label><label><span>Notes</span><textarea value={v.notes} onChange={(e:any)=>setV({...v,notes:e.target.value})}/></label></div><div className="modal-foot"><button className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={!v.venueId} onClick={()=>{onSave({...v,id:`visit_${Date.now()}`,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});onClose()}}>Start</button></div></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><strong>{title}</strong><button className="icon-btn small" onClick={onClose}>×</button></div>{children}</div></div>}
