import type { Collection, LifeData, Location, Observation, Taxon, Trip, Venue, Visit } from './types';
import { canonicalize, emptyData, makeId, normalizeTaxon, now } from './store-core';
import { sameCanonicalTaxon } from './taxonomy-utils';
const KEY='life:v3';
export { makeId };
function validDate(value:string,precision='DAY'){if(!value)return precision==='UNKNOWN';if(precision==='DAY'){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!m)return false;const d=new Date(Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3])));return d.getUTCFullYear()===Number(m[1])&&d.getUTCMonth()===Number(m[2])-1&&d.getUTCDate()===Number(m[3]);}if(precision==='MONTH'){const m=/^(\d{4})-(\d{2})$/.exec(value);return Boolean(m)&&Number(m[2])>=1&&Number(m[2])<=12;}if(precision==='YEAR')return /^\d{4}$/.test(value);return true;}
function normalizeObservation(o:Observation,d:LifeData,existing?:Observation):Observation{if(!d.taxa[o.taxonId])throw new Error('Taxon is not cached.');if(o.venueId&&!d.venues.some(v=>v.id===o.venueId))throw new Error('Venue reference is invalid.');if(o.tripId&&!d.trips.some(t=>t.id===o.tripId))throw new Error('Trip reference is invalid.');if(o.visitId&&!d.visits.some(v=>v.id===o.visitId))throw new Error('Visit reference is invalid.');if(o.visitId){const v=d.visits.find(x=>x.id===o.visitId);if(v&&o.venueId&&v.venueId!==o.venueId)throw new Error('Visit and venue do not match.');if(v&&!o.venueId)o={...o,venueId:v.venueId};}if(!validDate(o.observedDate,o.datePrecision??'DAY'))throw new Error('Observation date does not match its precision.');return{...o,id:o.id||existing?.id||makeId('obs'),datePrecision:o.datePrecision??'DAY',approximate:Boolean(o.approximate),count:Math.max(1,Math.floor(Number(o.count)||1)),notes:String(o.notes??''),createdAt:existing?.createdAt||o.createdAt||now(),updatedAt:now()};}
export function loadData():LifeData{if(typeof window==='undefined')return emptyData();try{const raw=localStorage.getItem(KEY);if(raw)return canonicalize(JSON.parse(raw));for(const key of ['life:v2','life:v1']){const legacy=localStorage.getItem(key);if(legacy){const data=canonicalize({...emptyData(),...JSON.parse(legacy)});writeData(data);return data;}}}catch{}return emptyData();}
export function writeData(data:LifeData){if(typeof window!=='undefined')localStorage.setItem(KEY,JSON.stringify(canonicalize(data)));}
export function persist(data:LifeData){const next=canonicalize(data);writeData(next);return next;}
export function saveObservation(o:Observation,d:LifeData){const observation=normalizeObservation(o,d);return persist({...d,observations:[observation,...d.observations],recentTaxonIds:[o.taxonId,...d.recentTaxonIds.filter(x=>x!==o.taxonId)].slice(0,30)});}
export function updateObservation(o:Observation,d:LifeData){const existing=d.observations.find(x=>x.id===o.id);if(!existing)throw new Error('Observation not found.');const observation=normalizeObservation(o,d,existing);return persist({...d,observations:d.observations.map(x=>x.id===o.id?observation:x)});}
export function deleteObservation(id:string,d:LifeData){return persist({...d,observations:d.observations.filter(x=>x.id!==id),media:d.media.filter(m=>m.observationId!==id)});}
function upsert<T extends Location|Venue|Trip|Visit|Collection>(key:'locations'|'venues'|'trips'|'visits'|'collections',item:T,d:LifeData){const array=d[key] as unknown as T[];if(!item.id)throw new Error('Record id is required.');if(key==='visits'){const v=item as unknown as Visit;if(!d.venues.some(x=>x.id===v.venueId))throw new Error('Visit venue does not exist.');if(v.tripId&&!d.trips.some(x=>x.id===v.tripId))throw new Error('Visit trip does not exist.');}if(key==='collections'&&!String((item as Collection).name||'').trim())throw new Error('Collection name is required.');const next=array.some(x=>x.id===item.id)?array.map(x=>x.id===item.id?item:x):[item,...array];return persist({...d,[key]:next} as LifeData);}
export const upsertLocation=(item:Location,d:LifeData)=>upsert('locations',item,d);export const upsertVenue=(item:Venue,d:LifeData)=>upsert('venues',item,d);export const upsertTrip=(item:Trip,d:LifeData)=>upsert('trips',item,d);export const upsertVisit=(item:Visit,d:LifeData)=>upsert('visits',item,d);export const upsertCollection=(item:Collection,d:LifeData)=>upsert('collections',item,d);
export function deleteCollection(id:string,d:LifeData){return persist({...d,collections:d.collections.filter(x=>x.id!==id)});}
export function setTargets(ids:string[],d:LifeData){return persist({...d,targets:[...new Set(ids)].filter(id=>Boolean(d.taxa[id]))});}
export function upsertTaxon(t:Taxon,d:LifeData){const data=canonicalize(d);const incoming=normalizeTaxon(t);const match=Object.values(data.taxa).find(x=>sameCanonicalTaxon(x,incoming));const merged=match?{...match,...incoming,commonNames:[...new Map([...match.commonNames,...incoming.commonNames].map(x=>[x.name.toLowerCase(),x])).values()]}:incoming;return persist({...data,taxa:{...data.taxa,[merged.id]:merged},recentTaxonIds:[merged.id,...data.recentTaxonIds.filter(id=>id!==merged.id)].slice(0,30)});}
export function replaceData(data:LifeData){return persist({...emptyData(),...data});}
export function clearData(){const data=emptyData();writeData(data);return data;}
