import type { LifeData, LifeListItem, Milestone, Observation, QueryDefinition, Taxon } from './types';
import { normalizeTaxonomyText } from './taxonomy-utils';
export const taxonName=(t:Taxon)=>t.commonNames[0]?.name||t.canonicalName;
const dkey=(o:Observation)=>o.observedDate||'9999-99-99';
export function buildLifeList(d:LifeData):LifeListItem[]{const m=new Map<string,Observation[]>();for(const o of d.observations)if(d.taxa[o.taxonId])m.set(o.taxonId,[...(m.get(o.taxonId)??[]),o]);return [...m].map(([id,obs])=>{const ordered=[...obs].sort((a,b)=>dkey(a).localeCompare(dkey(b))||a.createdAt.localeCompare(b.createdAt));return{taxon:d.taxa[id],observations:obs,firstObservation:ordered[0],lastObservation:ordered.at(-1)!,observationCount:obs.length,individualCount:obs.reduce((n,o)=>n+Math.max(1,o.count),0),countries:[...new Set(obs.map(o=>o.country??o.locationSnapshot?.country).filter(Boolean) as string[])],venues:[...new Set(obs.map(o=>o.venueId).filter(Boolean) as string[])]};}).sort((a,b)=>dkey(a.firstObservation).localeCompare(dkey(b.firstObservation))||a.taxon.canonicalName.localeCompare(b.taxon.canonicalName));}
export function queryObservations(d:LifeData,q:QueryDefinition={}):Observation[]{const life=buildLifeList(d), counts=new Map(life.map(x=>[x.taxon.id,x.observationCount]));return d.observations.filter(o=>{const t=d.taxa[o.taxonId];if(!t)return false;const text=normalizeTaxonomyText([taxonName(t),t.canonicalName,t.scientificName,t.genus,t.family,t.order,t.className,...t.synonyms,o.notes,o.city,o.country,o.locationSnapshot?.name].filter(Boolean).join(' '));if(q.text&&!text.includes(normalizeTaxonomyText(q.text)))return false;for(const k of ['kingdom','phylum','className','order','family','genus'] as const)if(q[k]&&normalizeTaxonomyText(t[k]??'')!==normalizeTaxonomyText(q[k]!))return false;if(q.taxonId&&o.taxonId!==q.taxonId)return false;if(q.country&&(o.country??o.locationSnapshot?.country)!==q.country)return false;if(q.city&&(o.city??o.locationSnapshot?.city)!==q.city)return false;if(q.venueId&&o.venueId!==q.venueId)return false;if(q.venueType){const v=o.venueId?d.venues.find(x=>x.id===o.venueId):undefined;if((v?.type??o.locationSnapshot?.venueType)!==q.venueType)return false;}if(q.year&&Number(o.observedDate.slice(0,4))!==q.year)return false;if(q.month&&Number(o.observedDate.slice(5,7))!==q.month)return false;if(q.from&&o.observedDate<q.from)return false;if(q.to&&o.observedDate>q.to)return false;if(q.includeApproximate===false&&o.approximate)return false;if(q.observationType&&o.observationType!==q.observationType)return false;if(q.minCount!=null&&o.count<q.minCount)return false;if(q.maxCount!=null&&o.count>q.maxCount)return false;if(q.evidence&&(o.evidence??'UNVERIFIED')!==q.evidence)return false;if(q.confidence&&(o.confidence??'CERTAIN')!==q.confidence)return false;if(q.hasPhoto!=null&&(Boolean(o.photoIds?.length)!==q.hasPhoto))return false;if(q.seenExactlyOnce&&counts.get(o.taxonId)!==1)return false;if(q.seenMultipleTimes&&!(counts.get(o.taxonId)!&&counts.get(o.taxonId)!>1))return false;return true;});}
export const queryLifeList=(d:LifeData,q:QueryDefinition={})=>{const ids=new Set(queryObservations(d,q).map(o=>o.taxonId));return buildLifeList(d).filter(x=>ids.has(x.taxon.id));};
export const evaluateCollection=(d:LifeData,c:{queryDefinition:QueryDefinition})=>queryLifeList(d,c.queryDefinition);
export function milestones(d:LifeData):Milestone[]{const life=buildLifeList(d),out:Milestone[]=[];for(let i=0;i<life.length;i++){const n=i+1;if(n===1||n%100===0)out.push({id:`species-${n}`,type:'species',title:`${n.toLocaleString()} species`,date:life[i].firstObservation.observedDate,taxonId:life[i].taxon.id,value:n,detail:`${taxonName(life[i].taxon)} was species #${n}.`});}const first=[['mammal','Mammal','Mammalia'],['bird','Bird','Aves'],['wild','Wild species','Wild']] as const;for(const [id,label,val] of first){const x=life.find(i=>id==='wild'?i.observations.some(o=>o.observationType==='Wild'):i.taxon.className===val);if(x)out.push({id:`first-${id}`,type:'first',title:`First ${label}`,date:x.firstObservation.observedDate,taxonId:x.taxon.id,detail:taxonName(x.taxon)});}const countries=[...new Set(d.observations.map(o=>o.country??o.locationSnapshot?.country).filter(Boolean) as string[])];for(const c of countries){const x=life.find(i=>i.countries.includes(c));if(x)out.push({id:`country-${c}`,type:'country',title:`First species in ${c}`,date:x.firstObservation.observedDate,taxonId:x.taxon.id,detail:taxonName(x.taxon)});}return out.sort((a,b)=>String(a.date??'').localeCompare(String(b.date??''))||a.title.localeCompare(b.title));}
