import type { Species } from './types';

export const species: Species[] = [
  {id:'lion',commonName:'Lion',scientificName:'Panthera leo',genus:'Panthera',family:'Felidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'tiger',commonName:'Tiger',scientificName:'Panthera tigris',genus:'Panthera',family:'Felidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'leopard',commonName:'Leopard',scientificName:'Panthera pardus',genus:'Panthera',family:'Felidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'cheetah',commonName:'Cheetah',scientificName:'Acinonyx jubatus',genus:'Acinonyx',family:'Felidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'giraffe',commonName:'Giraffe',scientificName:'Giraffa camelopardalis',genus:'Giraffa',family:'Giraffidae',order:'Artiodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'okapi',commonName:'Okapi',scientificName:'Okapia johnstoni',genus:'Okapia',family:'Giraffidae',order:'Artiodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'african-elephant',commonName:'African savanna elephant',scientificName:'Loxodonta africana',genus:'Loxodonta',family:'Elephantidae',order:'Proboscidea',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'asian-elephant',commonName:'Asian elephant',scientificName:'Elephas maximus',genus:'Elephas',family:'Elephantidae',order:'Proboscidea',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'white-rhino',commonName:'White rhinoceros',scientificName:'Ceratotherium simum',genus:'Ceratotherium',family:'Rhinocerotidae',order:'Perissodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Near Threatened'},
  {id:'black-rhino',commonName:'Black rhinoceros',scientificName:'Diceros bicornis',genus:'Diceros',family:'Rhinocerotidae',order:'Perissodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Critically Endangered'},
  {id:'hippo',commonName:'Hippopotamus',scientificName:'Hippopotamus amphibius',genus:'Hippopotamus',family:'Hippopotamidae',order:'Artiodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'gorilla',commonName:'Western gorilla',scientificName:'Gorilla gorilla',genus:'Gorilla',family:'Hominidae',order:'Primates',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Critically Endangered'},
  {id:'chimpanzee',commonName:'Chimpanzee',scientificName:'Pan troglodytes',genus:'Pan',family:'Hominidae',order:'Primates',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'orangutan',commonName:'Bornean orangutan',scientificName:'Pongo pygmaeus',genus:'Pongo',family:'Hominidae',order:'Primates',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Critically Endangered'},
  {id:'red-panda',commonName:'Red panda',scientificName:'Ailurus fulgens',genus:'Ailurus',family:'Ailuridae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'polar-bear',commonName:'Polar bear',scientificName:'Ursus maritimus',genus:'Ursus',family:'Ursidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'brown-bear',commonName:'Brown bear',scientificName:'Ursus arctos',genus:'Ursus',family:'Ursidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'meerkat',commonName:'Meerkat',scientificName:'Suricata suricatta',genus:'Suricata',family:'Herpestidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'otter',commonName:'Eurasian otter',scientificName:'Lutra lutra',genus:'Lutra',family:'Mustelidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Near Threatened'},
  {id:'red-kangaroo',commonName:'Red kangaroo',scientificName:'Osphranter rufus',genus:'Osphranter',family:'Macropodidae',order:'Diprotodontia',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'koala',commonName:'Koala',scientificName:'Phascolarctos cinereus',genus:'Phascolarctos',family:'Phascolarctidae',order:'Diprotodontia',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'giant-panda',commonName:'Giant panda',scientificName:'Ailuropoda melanoleuca',genus:'Ailuropoda',family:'Ursidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'sloth',commonName:'Linnaeus’s two-toed sloth',scientificName:'Choloepus didactylus',genus:'Choloepus',family:'Choloepodidae',order:'Pilosa',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'capybara',commonName:'Capybara',scientificName:'Hydrochoerus hydrochaeris',genus:'Hydrochoerus',family:'Caviidae',order:'Rodentia',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'zebra',commonName:'Plains zebra',scientificName:'Equus quagga',genus:'Equus',family:'Equidae',order:'Perissodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Near Threatened'},
  {id:'tapir',commonName:'Malayan tapir',scientificName:'Tapirus indicus',genus:'Tapirus',family:'Tapiridae',order:'Perissodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'red-deer',commonName:'Red deer',scientificName:'Cervus elaphus',genus:'Cervus',family:'Cervidae',order:'Artiodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'wild-boar',commonName:'Wild boar',scientificName:'Sus scrofa',genus:'Sus',family:'Suidae',order:'Artiodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'common-seal',commonName:'Harbour seal',scientificName:'Phoca vitulina',genus:'Phoca',family:'Phocidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'bottlenose',commonName:'Common bottlenose dolphin',scientificName:'Tursiops truncatus',genus:'Tursiops',family:'Delphinidae',order:'Cetacea',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'european-bison',commonName:'European bison',scientificName:'Bison bonasus',genus:'Bison',family:'Bovidae',order:'Artiodactyla',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Near Threatened'},
  {id:'red-fox',commonName:'Red fox',scientificName:'Vulpes vulpes',genus:'Vulpes',family:'Canidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'grey-wolf',commonName:'Grey wolf',scientificName:'Canis lupus',genus:'Canis',family:'Canidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'badger',commonName:'European badger',scientificName:'Meles meles',genus:'Meles',family:'Mustelidae',order:'Carnivora',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'beaver',commonName:'Eurasian beaver',scientificName:'Castor fiber',genus:'Castor',family:'Castoridae',order:'Rodentia',className:'Mammalia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'osprey',commonName:'Osprey',scientificName:'Pandion haliaetus',genus:'Pandion',family:'Pandionidae',order:'Accipitriformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'golden-eagle',commonName:'Golden eagle',scientificName:'Aquila chrysaetos',genus:'Aquila',family:'Accipitridae',order:'Accipitriformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'peregrine',commonName:'Peregrine falcon',scientificName:'Falco peregrinus',genus:'Falco',family:'Falconidae',order:'Falconiformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'bald-eagle',commonName:'Bald eagle',scientificName:'Haliaeetus leucocephalus',genus:'Haliaeetus',family:'Accipitridae',order:'Accipitriformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'penguin',commonName:'African penguin',scientificName:'Spheniscus demersus',genus:'Spheniscus',family:'Spheniscidae',order:'Sphenisciformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'flamingo',commonName:'Greater flamingo',scientificName:'Phoenicopterus roseus',genus:'Phoenicopterus',family:'Phoenicopteridae',order:'Phoenicopteriformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'emu',commonName:'Emu',scientificName:'Dromaius novaehollandiae',genus:'Dromaius',family:'Casuariidae',order:'Casuariiformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'cassowary',commonName:'Southern cassowary',scientificName:'Casuarius casuarius',genus:'Casuarius',family:'Casuariidae',order:'Casuariiformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'ostrich',commonName:'Common ostrich',scientificName:'Struthio camelus',genus:'Struthio',family:'Struthionidae',order:'Struthioniformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'great-owl',commonName:'Eurasian eagle-owl',scientificName:'Bubo bubo',genus:'Bubo',family:'Strigidae',order:'Strigiformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'toucan',commonName:'Toco toucan',scientificName:'Ramphastos toco',genus:'Ramphastos',family:'Ramphastidae',order:'Piciformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'macaw',commonName:'Blue-and-yellow macaw',scientificName:'Ara ararauna',genus:'Ara',family:'Psittacidae',order:'Psittaciformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'scarlet-ibis',commonName:'Scarlet ibis',scientificName:'Eudocimus ruber',genus:'Eudocimus',family:'Threskiornithidae',order:'Pelecaniformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'king-penguin',commonName:'King penguin',scientificName:'Aptenodytes patagonicus',genus:'Aptenodytes',family:'Spheniscidae',order:'Sphenisciformes',className:'Aves',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'green-anaconda',commonName:'Green anaconda',scientificName:'Eunectes murinus',genus:'Eunectes',family:'Boidae',order:'Squamata',className:'Reptilia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'reticulated-python',commonName:'Reticulated python',scientificName:'Malayopython reticulatus',genus:'Malayopython',family:'Pythonidae',order:'Squamata',className:'Reptilia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'komodo-dragon',commonName:'Komodo dragon',scientificName:'Varanus komodoensis',genus:'Varanus',family:'Varanidae',order:'Squamata',className:'Reptilia',kingdom:'Animalia',conservationStatus:'Endangered'},
  {id:'green-iguana',commonName:'Green iguana',scientificName:'Iguana iguana',genus:'Iguana',family:'Iguanidae',order:'Squamata',className:'Reptilia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'galapagos-tortoise',commonName:'Galápagos tortoise',scientificName:'Chelonoidis niger',genus:'Chelonoidis',family:'Testudinidae',order:'Testudines',className:'Reptilia',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'nile-crocodile',commonName:'Nile crocodile',scientificName:'Crocodylus niloticus',genus:'Crocodylus',family:'Crocodylidae',order:'Crocodylia',className:'Reptilia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'poison-frog',commonName:'Blue poison frog',scientificName:'Dendrobates tinctorius',genus:'Dendrobates',family:'Dendrobatidae',order:'Anura',className:'Amphibia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'axolotl',commonName:'Axolotl',scientificName:'Ambystoma mexicanum',genus:'Ambystoma',family:'Ambystomatidae',order:'Caudata',className:'Amphibia',kingdom:'Animalia',conservationStatus:'Critically Endangered'},
  {id:'common-frog',commonName:'Common frog',scientificName:'Rana temporaria',genus:'Rana',family:'Ranidae',order:'Anura',className:'Amphibia',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'clownfish',commonName:'Ocellaris clownfish',scientificName:'Amphiprion ocellaris',genus:'Amphiprion',family:'Pomacentridae',order:'Perciformes',className:'Actinopterygii',kingdom:'Animalia',conservationStatus:'Least Concern'},
  {id:'seahorse',commonName:'Common seahorse',scientificName:'Hippocampus kuda',genus:'Hippocampus',family:'Syngnathidae',order:'Syngnathiformes',className:'Actinopterygii',kingdom:'Animalia',conservationStatus:'Vulnerable'},
  {id:'arapaima',commonName:'Arapaima',scientificName:'Arapaima gigas',genus:'Arapaima',family:'Arapaimidae',order:'Osteoglossiformes',className:'Actinopterygii',kingdom:'Animalia',conservationStatus:'Data Deficient'},
  {id:'atlas-moth',commonName:'Atlas moth',scientificName:'Attacus atlas',genus:'Attacus',family:'Saturniidae',order:'Lepidoptera',className:'Insecta',kingdom:'Animalia',conservationStatus:'Not Evaluated'},
  {id:'emperor-scorpion',commonName:'Emperor scorpion',scientificName:'Pandinus imperator',genus:'Pandinus',family:'Scorpionidae',order:'Scorpiones',className:'Arachnida',kingdom:'Animalia',conservationStatus:'Least Concern'},
];

export const speciesById = new Map(species.map((item) => [item.id, item]));
